//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoParqueoUSAM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.TICKET = new HashSet<TICKET>();
        }

        [DisplayName("Codigo Cliente")]
        public int ID_CLIENTE { get; set; }
        [DisplayName("Nombre del Cliente")]
        public string NOMBRE_CLIENTE { get; set; }
        public string VEHICULO { get; set; }
        [DisplayName("Numero de Placa")]
        public string NUM_PLACA { get; set; }
        [DisplayName("# Parqueo")]
        public int ID_PARQUEO { get; set; }

        public virtual LUGAR_PARQUEO LUGAR_PARQUEO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKET> TICKET { get; set; }
    }
}
