//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoParqueoUSAM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_PARQUEO2Entities : DbContext
    {
        public BD_PARQUEO2Entities()
            : base("name=BD_PARQUEO2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<LUGAR_PARQUEO> LUGAR_PARQUEO { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<TICKET> TICKET { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
