//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoParqueoUSAM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USUARIO
    {
        public int ID_USUARIO { get; set; }
        public int ID_ROL { get; set; }
        [Required(ErrorMessage = "Usuario es requerido")]
        public string USUARIO1 { get; set; }
        [Required(ErrorMessage = "Favor ingrese la contraseña")]
        [DataType(DataType.Password)]

        public string PASSWORD { get; set; }
    
        public virtual ROLES ROLES { get; set; }
    }
}
