//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_ParqueoUSAM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TICKET
    {
        public int ID_TICKET { get; set; }
        public int ID_CLIENTE { get; set; }
        public int ID_PARQUEO { get; set; }
        [DisplayName("Hora O Fraccion")]
        public string TIPO_TICKET { get; set; }
        public System.DateTime FECHA { get; set; }
        [DisplayName("Tiempo en Horas")]
        public decimal TIEMPO_PARQUEO { get; set; }
        [DisplayName("Total a Pagar")]
        public decimal COSTO_FINAL { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual LUGAR_PARQUEO LUGAR_PARQUEO { get; set; }


        public string SoloFecha
        {
            get { return this.FECHA.ToString("MM/dd/yyyy"); }
        }
        public string SoloHora
        {
            get { return this.TIEMPO_PARQUEO.ToString("HH:mm tt"); }
        }
        
        public double TotalPago
        {
            get { return Convert.ToDouble(this.TIEMPO_PARQUEO) *  0.75; }
        }
    }
}
